import type { Event } from "@/types"

export const SAMPLE_EVENTS: Event[] = [
  {
    id: 1,
    gymName: "Capital Gymnastics - Cedar Park",
    gymAddress: "Cedar Park, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/capgymavery",
    title: "Kids Night Out Summer Fun!",
    date: "June 11, 2025",
    time: "6:30 PM - 9:30 PM",
    price: "$35",
    day: "Wednesday",
    type: "KIDS NIGHT OUT",
    url: "https://portal.iclasspro.com/capgymavery/camp-details/1091",
  },
  {
    id: 2,
    gymName: "Capital Gymnastics - Cedar Park",
    gymAddress: "Cedar Park, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/capgymavery",
    title: "Kids Night Out Flippin' Fun!",
    date: "June 25, 2025",
    time: "6:30 PM - 9:30 PM",
    price: "$35",
    day: "Wednesday",
    type: "KIDS NIGHT OUT",
    url: "https://portal.iclasspro.com/capgymavery/camp-details/1092",
  },
  {
    id: 3,
    gymName: "Capital Gymnastics - Cedar Park",
    gymAddress: "Cedar Park, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/capgymavery",
    title: "Back Handspring Skill Clinic",
    date: "June 3, 2025",
    time: "6:30 PM - 7:30 PM",
    price: "$25",
    day: "Tuesday",
    type: "CLINIC",
    url: "https://portal.iclasspro.com/capgymavery/camps/91?sortBy=time",
  },
  {
    id: 4,
    gymName: "Capital Gymnastics - Cedar Park",
    gymAddress: "Cedar Park, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/capgymavery",
    title: "Kip Skill Clinic",
    date: "June 17, 2025",
    time: "6:30 PM - 7:30 PM",
    price: "$25",
    day: "Tuesday",
    type: "CLINIC",
    url: "https://portal.iclasspro.com/capgymavery/camps/91?sortBy=time",
  },
  {
    id: 5,
    gymName: "Capital Gymnastics - Cedar Park",
    gymAddress: "Cedar Park, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/capgymavery",
    title: "Open Gym Session",
    date: "June 4, 2025",
    time: "10:30 AM - 12:00 PM",
    price: "$15",
    day: "Wednesday",
    type: "OPEN GYM",
    url: "https://portal.iclasspro.com/capgymavery/camp-details/1066",
  },
  {
    id: 6,
    gymName: "Capital Gymnastics - Cedar Park",
    gymAddress: "Cedar Park, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/capgymavery",
    title: "Camping Week Summer Camp",
    date: "June 2, 2025",
    time: "9:00 AM - 3:00 PM",
    price: "$295",
    day: "Monday",
    type: "Summer Camp",
    url: "https://portal.iclasspro.com/capgymavery/camp-details/1055",
  },
  {
    id: 7,
    gymName: "Capital Gymnastics - Pflugerville",
    gymAddress: "Pflugerville, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/capgymhp",
    title: "Kids Night Out",
    date: "June 11, 2025",
    time: "6:30 PM - 9:30 PM",
    price: "$35",
    day: "Wednesday",
    type: "KIDS NIGHT OUT",
    url: "https://portal.iclasspro.com/capgymhp/camp-details/1198",
  },
  {
    id: 8,
    gymName: "Houston Gymnastics Academy",
    gymAddress: "5201 Gulfton St., Houston, TX 77081",
    gymPhone: "(713) 668-6001",
    gymBookingPage: "https://portal.iclasspro.com/houstongymnastics",
    title: "Pirates & Princess Summer Camp",
    date: "June 23, 2025",
    time: "9:00 AM - 3:00 PM",
    price: "$295",
    day: "Monday",
    type: "Summer Camp",
    url: "https://portal.iclasspro.com/houstongymnastics/camp-details/738",
  },
  {
    id: 9,
    gymName: "Houston Gymnastics Academy",
    gymAddress: "5201 Gulfton St., Houston, TX 77081",
    gymPhone: "(713) 668-6001",
    gymBookingPage: "https://portal.iclasspro.com/houstongymnastics",
    title: "Gymnastics Skills Clinic",
    date: "June 5, 2025",
    time: "7:00 PM - 8:00 PM",
    price: "$25",
    day: "Thursday",
    type: "CLINIC",
    url: "https://portal.iclasspro.com/houstongymnastics/camps/2",
  },
  {
    id: 10,
    gymName: "Houston Gymnastics Academy",
    gymAddress: "5201 Gulfton St., Houston, TX 77081",
    gymPhone: "(713) 668-6001",
    gymBookingPage: "https://portal.iclasspro.com/houstongymnastics",
    title: "Kids Night Out Fun Night",
    date: "June 13, 2025",
    time: "6:00 PM - 9:00 PM",
    price: "$35",
    day: "Friday",
    type: "KIDS NIGHT OUT",
    url: "https://portal.iclasspro.com/houstongymnastics/camps/7",
  },
  {
    id: 11,
    gymName: "Estrella Gymnastics",
    gymAddress: "Houston, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/estrellagymnastics",
    title: "Pit Stop Summer Camp",
    date: "June 23, 2025",
    time: "9:00 AM - 3:00 PM",
    price: "$295",
    day: "Monday",
    type: "Summer Camp",
    url: "https://portal.iclasspro.com/estrellagymnastics/camp-details/453",
  },
  {
    id: 12,
    gymName: "Capital Gymnastics - Round Rock",
    gymAddress: "Round Rock, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/capgymroundrock",
    title: "Kids Night Out",
    date: "June 11, 2025",
    time: "6:30 PM - 9:30 PM",
    price: "$35",
    day: "Wednesday",
    type: "KIDS NIGHT OUT",
    url: "https://portal.iclasspro.com/capgymroundrock/camp-details/1418",
  },
  {
    id: 13,
    gymName: "Oasis Gymnastics",
    gymAddress: "Houston, TX",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/oasisgymnastics",
    title: "Open Gym Session",
    date: "June 14, 2025",
    time: "10:00 AM - 11:30 AM",
    price: "$15",
    day: "Saturday",
    type: "OPEN GYM",
    url: "https://portal.iclasspro.com/oasisgymnastics/camps/60",
  },
  {
    id: 14,
    gymName: "Scottsdale Gymnastics",
    gymAddress: "Scottsdale, AZ",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/scottsdalegymnastics",
    title: "Open Gym Fun",
    date: "June 21, 2025",
    time: "11:00 AM - 12:30 PM",
    price: "$15",
    day: "Saturday",
    type: "OPEN GYM",
    url: "https://portal.iclasspro.com/scottsdalegymnastics/camps/88",
  },
  {
    id: 15,
    gymName: "Tigar Gymnastics",
    gymAddress: "",
    gymPhone: "",
    gymBookingPage: "https://portal.iclasspro.com/tigar",
    title: "Open Gym Session",
    date: "June 28, 2025",
    time: "9:00 AM - 10:30 AM",
    price: "$15",
    day: "Saturday",
    type: "OPEN GYM",
    url: "https://portal.iclasspro.com/tigar/camps/22",
  },
]
